# Ejercicio 2: Lista de compras

print("Shopping List")
print("-------------")
print("1. Giacomo")
print("2. Papas McCain")
print("3. Alcohol")
print("4. Ajo")
print("5. Fruta")
print("6. Arroz")
print("7. Aceite de girasol")
print("8. Papel higiénico")
print("9. Puré de tomate")
print("10. Carne picada")
print("11. Cerveza")
print("12. Choclo")
print("13. Dulce de leche")
